### ISSUE TITLE
Bug: Cannot save note to Sqlite when the app is first time to use

### ISSUE THREAD

**Issue by jims57** [jims57/seal_note#630]

**Comment by jims57** [comment]
E/flutter (23035): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'reviewPlanId' was called on null.
E/flutter (23035): Receiver: null
E/flutter (23035): Tried calling: reviewPlanId
E/flutter (23035): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
E/flutter (23035): #1      NoteDetailWidgetState._getNextReviewTimeForNewNote (package:seal_note/ui/NoteDetailWidget.dart:1948:30)
E/flutter (23035): #2      new NoteDetailWidgetState.<anonymous closure> (package:seal_note/ui/NoteDetailWidget.dart:618:39)
E/flutter (23035): #3      new NoteDetailWidgetState.<anonymous closure> (package:seal_note/ui/NoteDetailWidget.dart:529:28)
E/flutter (23035): #4      FlutterWebviewPlugin._handleJavascriptChannelMessage (package:flutter_webview_plugin/src/base.dart:328:29)
E/flutter (23035): #5      FlutterWebviewPlugin._handleMessages (package:flutter_webview_plugin/src/base.dart:81:9)
E/flutter (23035): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:386:55)
E/flutter (23035): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:379:34)
E/flutter (23035): #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
E/flutter (23035): #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
E/flutter (23035): #10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
E/flutter (23035): #11     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (23035): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (23035): #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (23035): #14     _invoke2 (dart:ui/hooks.dart:204:10)
E/flutter (23035): #15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (23035): #16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (23035): #17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (23035): #18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
E/flutter (23035): #19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
E/flutter (23035):

**Comment by jims57** [comment]
I found `GlobalState.isNewNoteBeingSaved = true` sometimes when creating a new note.

**Comment by jims57** [comment]
![image](https://user-images.githubusercontent.com/1920873/144547478-0eaf91f3-e856-402f-8f6b-675ac81b915b.png)
